from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCKER_DIR = REPO_ROOT / "docker"
TOOLS_DIR = REPO_ROOT / "tools"
RECORDER_DIR = TOOLS_DIR / "recorder"
RESULTS_DIR = REPO_ROOT / "results"

DEFAULT_MINECRAFT_VERSION = "1.21.11"
DEFAULT_AGENT_USERNAME = "mcbench_agent"
DEFAULT_BASE_GAME_PORT = 25665
DEFAULT_BASE_RCON_PORT = 25675
DEFAULT_SANDBOX_MEMORY = "1g"
DEFAULT_SANDBOX_PIDS_LIMIT = 256
DEFAULT_RECORDER_USERNAME = "recorderbot"

REPLAYMOD_FILE_FORMAT_VERSION = 14
MINECRAFT_PROTOCOL_TO_VERSION = {
    774: DEFAULT_MINECRAFT_VERSION,
}
